### PR TITLE
[Upgrade] Vale to 0.6.2

### PR DESCRIPTION
**Pull request by jdkato**
This bumps Vale up to its latest release.

Thanks for hosting this, by the way!

### CODE REVIEW

**Comment by Kristinita** [comment]
@jdkato ,

### 1. Offer

I want add you to maintainers of Vale Chocolatey package.

### 2. Argumentation

You can quick update Chocolatey package of your program. You don't need wait, when I accept pull requests.

What do you think about this offer?

**Comment by jdkato** [comment]
That sounds good to me. 

I'm admittedly not very familiar with Chocolatey, though&mdash;so just let me know what I need to do.

**Comment by jdkato** [comment]
@Kristinita is there anything I can do to help with this?

**Comment by Kristinita** [comment]
> I'm admittedly not very familiar with Chocolatey, though—so just let me know what I need to do.

### 1. Chocolatey site

1. Please, register in **<https://chocolatey.org>**.
1. Tell me your username in Chocolatey.org, that I can add you to maintainers of Vale Chocolatey package.

### 2. Testing package

1. Update version, checksum and download URL as in this pull request.
1. Print in a terminal:

```bash
D:\SashaChocolatey\packages\Vale\tools>cd ..

D:\SashaChocolatey\packages\Vale>cpack "D:\SashaChocolatey\packages\Vale\vale.nuspec"
Chocolatey v0.10.3
Attempting to build package from 'vale.nuspec'.
Successfully created package 'D:\SashaChocolatey\packages\Vale\vale.0.8.1.nupkg'

D:\SashaChocolatey\packages\Vale>cinst "D:\SashaChocolatey\packages\Vale\vale.0.8.1.nupkg" -y
Chocolatey v0.10.3
Installing the following packages:
D:\SashaChocolatey\packages\Vale\vale.0.8.1.nupkg
By installing you accept licenses for the packages.

vale v0.8.1
vale package files install completed. Performing other installation steps.
Downloading Vale
  from 'https://github.com/ValeLint/vale/releases/download/0.8.1/vale.msi'
Progress: 100% - Completed download of C:\Users\SashaChernykh\AppData\Local\Temp\chocolatey\vale\0.8.1\vale.msi (3.88 MB).
Download of vale.msi (3.88 MB) completed.
Hashes match.
Installing Vale…
Vale has been installed.
Environment Vars (like PATH) have changed. Close/reopen your shell to
 see the changes (or in powershell/cmd.exe just type `refreshenv`).
 The install of vale was successful.
  Software installed as 'msi', install location is likely default.

Chocolatey installed 1/1 packages. 0 packages failed.
 See the log for details (D:\Chocolatey\logs\chocolatey.log).

D:\SashaChocolatey\packages\Vale>cuninst vale -y
Chocolatey v0.10.3
Uninstalling the following packages:
vale

vale v0.8.1
 Running auto uninstaller…
 Auto uninstaller has successfully uninstalled vale or detected previous uninstall.
 vale has been successfully uninstalled.
Environment Vars (like PATH) have changed. Close/reopen your shell to
 see the changes (or in powershell/cmd.exe just type `refreshenv`).

Chocolatey uninstalled 1/1 packages. 0 packages failed.
 See the log for details (D:\Chocolatey\logs\chocolatey.log).

D:\SashaChocolatey\packages\Vale>
```

Please, replace `D:\SashaChocolatey\packages\Vale\vale.nuspec` to your path to `vale.nuspec` file.

If you don't get errors (successful installation and uninstalling) as me → print `choco push` in a terminal → Vale will push to Chocolatey.org.

Also, you can push new version of Vale Chocolatey package to this my repository (I [**add you to collaborators**](https://help.github.com/articles/inviting-collaborators-to-a-personal-repository/)) or in any your own repository.

Thanks.

**Comment by jdkato** [comment]
Thanks for the detailed instructions!

My username on Chocolatey is `jdkato`.

**Comment by Kristinita** [comment]
@jdkato , I add you to maintainers list:

maintainers list

Thanks.

**Pull request merged**
