### PR TITLE
Fix tempurl

### PR DESCRIPTION
**Pull request by aronovgj**
Fix tempurl

### CODE REVIEW

**Comment by Kristinita** [comment]
@aronovgj , already I change installation source and [**successfully passed automatic testing**](https://chocolatey.org/packages/karen/3.6.9). Sorry, I did not push changes to remote repository.

Thanks.

**Comment by aronovgj** [comment]
I know. But the link is already broken again. Same reason as before I think:
http://files1.majorgeeks.com/c7cd76645c010b68b3aec48d236d5946/backup/ptreplicator-setup.exe

**Comment by aronovgj** [comment]
This cryptic `c7cd76645c010b68b3aec48d236d5946` in the middle of the link usually means that the link was created automatically and will change soon.

**Comment by Kristinita** [comment]
Thanks, all right, I understand.

**Comment by Kristinita** [comment]
Thanks, all right, I understand.

@aronovgj , you try to install your branch version of Karen's replicator in your machine?

**Comment by aronovgj** [comment]
```
C:\Users\me\Desktop\karen>cinst karen -s %cd%
Chocolatey v0.10.3
Installing the following packages:
karen
By installing you accept licenses for the packages.

karen v3.6.9
karen package files install completed. Performing other installation steps.
The package karen wants to run 'chocolateyinstall.ps1'.
Note: If you don't run this script, the installation will fail.
Note: To confirm automatically next time, use '-y' or consider setting
 'allowGlobalConfirmation'. Run 'choco feature -h' for more details.
Do you want to run the script?([Y]es/[N]o/[P]rint): Y

True
Downloading Karens Replicator
  from 'https://dw.uptodown.com/dwn/_Oqa3YSAK6cZNsNsigkMJNo00RqZUbzM2qxjsqWNfGtN
Ughmtq4R7L5FuChp8cF2RnVDqJfgiv0HzD3jBc2cnxAoBP1JPxWMXVqlSI6JueQp8o2dBd_x_dojoK9J
-WXV/9qA5B8BaXnQzNAk7CgcOt2nRSEKBPg0JvbK22eypWbamonvdlXkj3eSoiOO8IWByaU-L7B_5xg3
ogJ-Rmjf6EsHM3HbjUYoiFIYsvvtGg_m51adDpcpqIIk99MUXbbL3/qmeIemhyiroV1u7JpBmD40xN4g
dayGHG-SNOATPPpW9SLTVZk9ENK3nAqlC_OASBhXVzAJ4o0aKMqJUZKQwwEvHLMjJvSH1oeKebkdwx7-
ADGO0H3XChvFZav6NSt8CB/1GyCfwpKDTKrXM9BpTGAI2tvz6HvSoVi70JTisYwuQ3SBIFD4SKzRcwB1
Gx2LLHn/'
Progress: 100% - Completed download of C:\Users\me\AppData\Local\Temp\chocolat
ey\karen\3.6.9\karens-replicator-3-6-9-en.exe (1.94 MB).
Download of karens-replicator-3-6-9-en.exe (1.94 MB) completed.
Hashes match.
Installing Karens Replicator...
Karens Replicator has been installed.
 The install of karen was successful.
  Software installed as 'exe', install location is likely default.

Chocolatey installed 1/1 packages. 0 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

```

**Pull request merged**
